name: Continuous integration

on:
  pull_request:
    branches: [ ts-development ]

  push:
    branches: [ ts-development ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npm test
      - run: npm run build